<?php

/**
* Implementation of hook_perm().
*/
function studi_kpmg_perm() {
 return array('Edit KPMG Settings');
}

/**
* Implementation of hook_menu().
*/
function studi_kpmg_menu() {
$items = array();

$items['quiz'] = array(
	 'title' => t('KPMG Wissensquiz'),
	  'page callback'   => '_studi_kpmg_front',
	  'access callback' => TRUE,
      'file'            => 'studi_kpmg.pages.inc',
  );
$items['quiz/saved'] = array(
	 'title' => t('KPMG Wissensquiz'),
	  'page callback'   => '_studi_kpmg_mail_saved',
	  'access callback' => TRUE,
      'file'            => 'studi_kpmg.pages.inc',
  );


$items['quiz/game'] = array(
	'title' => t('KPMG Wissensquiz'),
	  'page callback'   => '_studi_kpmg_game',
	  'access callback' => TRUE,
    'file'            => 'studi_kpmg.pages.inc',
  );
$items['quiz/highscore'] = array(
	'title' => t('KPMG Wissensquiz'),
	  'page callback'   => '_studi_kpmg_highscore',
	  'access callback' => TRUE,
    'file'            => 'studi_kpmg.pages.inc',
  );
$items['quiz/highscore/infos'] = array(
	'title' => t('KPMG Wissensquiz'),
	  'page callback'   => '_studi_kpmg_highscore_infos',
	  'access callback' => TRUE,
    'file'            => 'studi_kpmg.pages.inc',
  );


return $items;
}


/**
 * Implementation of hook_block().
 */
function  studi_kpmg_block($op, $delta, $edit = array()) {
  switch ($op) {
    case 'list':
      $blocks = array();

      $blocks[0] = array(
        'info'  => 'KPMG: Rangliste ',
        'cache' => BLOCK_NO_CACHE,
      );

      return $blocks;
      break;
    case 'view':
      if ($delta == 0) {
        $block = array(
          'subject' => 'Rangliste',
          'content' => studi_jobs_section_block_0(),
        );
      }

      global $user;
      if ($user->uid == 792 || $user->uid == 1) {
        return $block;
      }
      break;
  }
}

function studi_kpmg_check_uni($uid){
	global $user;
	$result = db_result(db_query('SELECT uni FROM studi_kpmg_player WHERE uid = %d', $user->uid));
	if(!empty($result)){
			  return TRUE;
			  }
}